### ISSUE TITLE
subversion can't recognize path like "file://"

### ISSUE THREAD

**Issue by ShuguangSun** [msys2/MSYS2-packages#121]
I used svn-win32 before and made some local repository. Now I tried subversion in msys2 and it got some errors:

svn: warning: cannot set LC_CTYPE locale
svn: warning: environment variable LANG is CHS
svn: warning: please check that your locale name is correct
svn: E170000: Unable to connect to a repository at URL 'file://rshmszj001/U_sun$/My%20Documents/Codehouse/0datapre.sas'
svn: E170000: Unable to open an ra_local session to URL
svn: E170000: Local URL 'file://rshmszj001/U_sun$/My%20Documents/Codehouse/0datapre.sas' contains unsupported hostname

**Comment by ShuguangSun** [comment]
It is becaue the path constains spaces.
`
svnadmin create "c:/Users/suns/Documents/base/test/subv/sub ver"
cd subs
svn co "file:///c:/Users/suns/Documents/base/test/subv/sub ver"
`
error message:
svn: E170013: Unable to connect to a repository at URL 'file:///c:/Users/suns/Documents/base/test/subv/sub%20ver'
svn: E180001: Unable to open repository 'file:///c:/Users/suns/Documents/base/test/subv/sub%20ver'

FYI.
win32svn (https://sourceforge.net/projects/win32svn/files/) doesn't have the issue.

**Comment by kolewu** [comment]
It's not because of the spaces but the URL is missing the root-slash so that the first word is interpreted as a hostname. `file://` is the protocol and must be followed by the absolute path including the leading slash.

When in `/tmp` and there is a repo `test repo` (cannot be created on msys because of #3258, so i have created it somewhere else), then this works:
```
$ svn co file:///tmp/"test repo" test
Checked out revision 0.
```

**Comment by ShuguangSun** [comment]
Got it. Thanks
