### ISSUE TITLE
msys2 keeps hidden executables in C:\$Recycle.Bin

### ISSUE THREAD

**Issue by DenisPolygalov** [msys2/MSYS2-packages#1253]
День добрый Алексей and others.

I noticed that msys2 (and/or pacman) leaves 4 strangely named executables in Recycle Bin and execute them while running. The names of these executables crafted in a way user cannot see them when open the Recycle Bin by using Windows Explorer. These executables are not deleted from the Recycle Bin even after user did "Empty Recycle Bin" action. One executable is a renamed version of msys-2.0.dll and another one is a terminal application. The rest two are unknown (for me). Here is how it look like:
https://ibb.co/jMuHVd 
I have two questions regarding this:
1. WTF is this?
2. Don't you think it is kind of... not so polite to do this without mentioning on home page in big size font if this mechanism is _really_ necessary for msys2 functionality?

Regards,
Denis

**Comment by cbrt64** [comment]
One year later:
This was introduced in Cygwin for WinNT to delete files with open handles on Windows, in order to allow for POSIX-type behavior. If you run an exe from the console, and `rm` it while it's still running, it will move to the Recycle Bin so it appears to be successfully deleted, and a new file with the same name can take its place. This allows for Unix build scripts, etc., to run with maximal compatibility on a platform that does not allow deleting open files. MSYS2 of course does the same, being based on Cygwin.
Windows 10 recently introduced new functionality that does allow deleting open files, and Cygwin 3 takes advantage of it. See https://cygwin.com/cygwin-ug-net/ov-new.html (search for "recycle").

**Comment by DenisPolygalov** [comment]
Thank you very much for the information, really appreciate this, even 1 year later.
I guess it is correct to close this issue because it is describes expected behavior.

**Comment by mback2k** [comment]
Is it still the correct behaviour on current Windows 10 after the following Cygwin 3 commits have been merged https://github.com/msys2/Cygwin/commit/a7f392686b5b2091e8f555ff2a2d63443e1fcb1c and https://github.com/msys2/Cygwin/commit/9fa22dba558f5e3efd0bb719049491edcd7b5e0b?

**Comment by lukasf** [comment]
This still happens on the latest MSYS2 versions. And it breaks installing MSYS2 into docker containers.

Even if this behavior is required despite Cygwin merges, I still think that this is a bug: If the files are moved to recycle bin, then on process exit or at least on next launch, MSYS2 should cleanup these files. But right now, these files stay there forever. Not even emptying the recycle bin (as user action) gets rid of them.

And also, I think it is a really bad idea to place these files outside the MSYS2 installation folder, into a Windows system folder. The files should be put in a directory below the MSYS2 root, so MSYS2 can easily check if any such files are still there, and do cleanup on exit or next launch. A long enough random file name (GUID) would make sure that it will never collide with user code.

**Comment by TBBle** [comment]
It was lost in the discussion, but the reason this breaks MSYS2 install into containers is not that the files are in `C:\$Recycle.Bin`, but that the filenames needlessly contain invalid surrogate pairs, and Go's stdlib filesystem routines (and plenty of other things) fail to handle that.

**Comment by sskras** [comment]
@TBBle wrote:

> the filenames needlessly contain invalid surrogate pairs

Should the new MSYS2 issue be created then?

Also I wonder who created the filenames and how does their on-disk presentation looks like.

**Comment by sskras** [comment]
Thanks. Wow, looks quite ugly!

If it's technically correct (according to the NTFS spec, [which I am not sure](https://en.wikipedia.org/wiki/NTFS#Structure)):

> NTFS allows any sequence of 16-bit values for name encoding [...] except 0x0000. This means [...] the file system does not check whether a sequence is valid UTF-16 (it allows any sequence of [short](https://en.wikipedia.org/wiki/Integer_(computer_science)#Short_integer) values, not restricted to those in the Unicode standard). In Win32 namespace, any UTF-16 code units are case insensitive

... the next step would be to see what the Unicode standard says about it:
https://unicode.scarfboy.com/?s=%5Cu%7Bdc63%7D
> Looks like \u{1234} style escape for U+DC63
> ...however, 0xDC63 is an isolated surrogate, which is not valid. Ignoring

Seems like the pairs belong to **Low Surrogate Area**:
https://www.unicode.org/charts/PDF/UDC00.pdf
> Range: DC00-DFFF

But it must be preceded with High Surrogate to make general sense (by forming 32 bits to denote one code point):
https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Surrogates

Now that I know it's isolated surrogate, the following text from Wikipedia starts making sense to me:

> Isolated surrogate code points have no general interpretation; consequently, no character code charts or names lists are provided for this range. In the [Python programming language](https://en.wikipedia.org/wiki/Python_programming_language), individual surrogate codes are used to embed undecodable bytes in Unicode strings.[[11]](https://en.wikipedia.org/wiki/Universal_Character_Set_characters#cite_note-11)

So what's left now is to find what the wide-char WinAPI functions say about invalid UTF-16 strings / isolated surrogates, no?

I wonder if they doesn't break. Googling for [msdn "isolated surrogate"](https://www.google.com/search?q=msdn+%22isolated+surrogate%22) doesn't reveal much.

Except maybe this old and indirect mention – ["Avoid treating binary data as a String"](https://learn.microsoft.com/en-us/archive/blogs/shawnste/avoid-treating-binary-data-as-a-string#:~:text=The%20behavior%20of%20illegal%20Unicode%20sequences%20isn%27t%20always%20consistent%20or%20expected.):
(article from 09/26/2005 by Shawn Steele)

> any character D800 - DFFF is expected to be a High Surrogate immediately followed by a Low Surrogate. Encountered separately the characters cause a String to become invalid Unicode. The behavior of illegal Unicode sequences isn't always consistent or expected. Additionally Unicode 4.0 forbids emitting illegal Unicode, so .Net v2.0 doesn't convert those values when doing UTF8 conversions.

So my guess is that most of WinAPI functions would either fail after parsing this string or just forward it to some NTAPI (which probably would fail too).

Using "WinAPI" or "WineHQ", or "ReactOS" in my Google query didn't work either.
I guess only the real API tests would tell the truth.

OTOH, if this code creates files using such filenames, what code does their removal/deletion and why it succeeds?

I don't know the situation good enough, but maybe Cygwin/MSYS2 themselves can be used to remove these filenames (before the Go runtime starts choking on them)?

**Comment by sskras** [comment]
PS. Summary of my idea:

If the Cygwin binary created files that no other programs should access, maybe it should finish the work and clean them up itself ?

**Comment by sskras** [comment]
@TBBle, thanks for your time and the thorough explanation!

Before it I got core of the issue wrong. Now I would summarize that non-valid UTF-16 names are a bit of a grey-zone:

they can work (if you don't try to interpret them), also they can break things. And there is no official API requirement for the names to be strictly UTF-16. :(

> These filenames are mainly problematic when using a cross-platform library or programming language (Go's stdlib and Node.js's stdlib are examples of this) which assumes that the OS-specific layer can convert any valid filename to and from, e.g., UTF-8, which is technically not-true in NTFS, but takes _specific_ effort (or disk corruption) to actually occur.

This reminds me of some proposal I heard many years ago – WTF-8:
https://simonsapin.github.io/wtf-8/

> WTF-8 (Wobbly Transformation Format − 8-bit) is a superset of [UTF-8](https://simonsapin.github.io/wtf-8/#utf-8) that encodes [surrogate code points](https://simonsapin.github.io/wtf-8/#surrogate-code-point) if they are not in a [pair](https://simonsapin.github.io/wtf-8/#surrogate-code-point-pair). It represents, in a way compatible with UTF-8, text from systems such as JavaScript and Windows that use [UTF-16](https://simonsapin.github.io/wtf-8/#utf-16) internally but don’t enforce the [well-formedness](https://simonsapin.github.io/wtf-8/#well-formed) invariant that surrogates must be paired.

  [...]

> ### 1. Intended audience
> [WTF-8](https://simonsapin.github.io/wtf-8/#wtf-8) is a hack intended to be used internally in self-contained systems with components that need to support [potentially ill-formed UTF-16](https://simonsapin.github.io/wtf-8/#potentially-ill-formed-utf-16) for legacy reasons.

I guess Go would have used WTF-8 format/codec instead of the UTF-8, the things would go nice.
Or this I also got wrong:)?

**Comment by TBBle** [comment]
I think you're right that if WTF-8 had been used, we wouldn't have this problem here. Apparently that's what's underlying Rust's OSString implementation.

I had a quick look, and [Python's file encoding history is... exciting](https://vstinner.github.io/python36-utf8-windows.html). I'm not sure, but based on [the proposal](https://peps.python.org/pep-0529/#proposal) I think Python 3 will reject paths with invalid surrogate pairs though. >_<

That said, I wouldn't really want WTF-8 to be the core string format of a systems programming language like Go, which frequently needs to interface with other languages that expect a "string" array of bytes to be UTF-8, as then you need to do [_something_ non-trivial](https://simonsapin.github.io/wtf-8/#converting-wtf-8-utf-8) at each such interface boundary. It definitely makes sense for a filename-holding type that needs to be usefully functional on Windows and non-Windows.

**Comment by sskras** [comment]
OK, I am trying to calm down. Just one note:

> Given a magic wand to flip the universe overnight? It might be okay, I haven't thought about it too hard, but if everyone was using WTF-8, instead of UTF-8

I more interested in this guesstimate: what part of UTF-8 apps would break if I feed them with not-well formed UTF-8 filenames?

IOW, maybe most of the libs that work with filenames just ignore the encoding?

PS. Also I leave some of my findings here that gives useful insights about WTF-8 / fixing the situation globally:

- [Charset Transcoding, Transformation, and Transliteration](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1439r0.pdf) (by Steve Downey | January 21, 2019)
- https://github.com/vitiral/stfu8 (kind of WTF-8 alternative by Rett Berg | 2018)
- https://dwheeler.com/essays/fixing-unix-linux-filenames.html (David A. Wheeler | 2020-11-15, originally 2009-03-24)
