### ISSUE TITLE
FR: Ncdu

### ISSUE THREAD

**Issue by gerroon** [msys2/MSYS2-packages#1538]
Hi

It would be nice if Ncdu is included in the repo.

https://dev.yorhel.nl/ncdu

**Comment by Alexpux** [comment]
@gerroon it can be in repo if you create and provide package script for it and will maintain it in future. This is how open source world works. In other case you must wait if someone interested in it and will do this work for you. I will not do it myself in any case

**Comment by gerroon** [comment]
I did not demand it.

 If anyone wants to make it cool, I am not skilled enough to pull this off

**Comment by mingwandroid** [comment]
You probably are skilled enough, or at least trying to add it will make you much more skilled in this activity for next time. You can also ask for help on gitter if you try it and run into problems.

**Comment by andrew-grechkin** [comment]
#1539 this should be enough

**Comment by dereksz66** [comment]
Hi @gerroon - did you get anywhere with this?  I also miss ncdu on MSYS2.  May be willing to pick it up...  INterested if you got anywhere or hit any walls.

**Comment by gerroon** [comment]
I was not skilled enough to pull this off. Thanks for asking.

**Comment by jimiwills** [comment]
Hello.  Since this is still pending, and I too prefer ncdu to WinDirStat, I will attempt to make a package (how hard can it be?)  I'm not gonna promise to support all cross-compilable platforms though!  Unless that's somehow compulsory.  I'll build for mingw-w64-x86_64 and see where we go from there.

**Comment by Biswa96** [comment]
Hi @jimiwills Thank you for bumping this issue. The ncdu program seems to be made for Unix-like operating systems. So, using msys2/cygwin layer would be a right choice here. I am not sure how well the ncdu program behaves under that compatibility layer. I have added a pull request (link above) to add this package. You can download the CI artifact and install the package with `pacman -U` command.

**Comment by jimiwills** [comment]
Hi
I compiled it on a fresh system with just mingw-w64-x86_64-toolchain, gcc, make, ,ncurses, ncurses-devel.  IFAIK there's no test suite?!  But it seems to work fine so far.  Currently scanning my windows user folder.  Previously scanned and reported a much smaller folder and browsing worked fine.
I'm fine with compiling simple programmes like that, but I guess others are still looking for a package.
I recently started a course on CI/CD, and so I actually now know what a CI artefact is, at least in principle.  I'll have a look and see what happens.  Thanks!

**Comment by andrew-grechkin** [comment]
@Biswa96 My PR to add this package is stuck here for almost 2.5 years (since 1 Jan 2019)
It's obvious that msys2 project is dead.
I would suggest using WSL or just switch to a Linux system

**Comment by Biswa96** [comment]
Me too would always suggest to use any GNU/Linux distribution or any Unix-like operating system over Micro$oft Windows. msys2 project does not focus on msys2 (fork of cygwin) layer. MSYS2-packages is just to support the Win32 native MINGW toolchain (compiler, linker, build system).

**Comment by jimiwills** [comment]
@Biswa96 aha, I see.  I did have WSL, but kinda ran out of room (partly because of shrinking partition to make space for ubuntu)  It's on my work device, and I need windows to interface with certain data/hardware, unfortunately.
But, yeah, the whole ncdu thing is clearly just because people like the tool and want to have it on their windows systems.  Being stuck with the windows system, there are loads of other tool I want here too.  Most of the other (technologically locked in) Windows work devices I have cygwin on for exactly that reason :)
Thanks again.

**Comment by Biswa96** [comment]
The ncdu package is now in pacman repository. One can download it with `pacman -S ncdu` command.
