### ISSUE TITLE
tar hangs on packages

### ISSUE THREAD

**Issue by mkroening** [msys2/MSYS2-packages#1548]
For about two days `tar` hangs on MSYS2 and MINGW packages which contain binaries on Windows 10 1809.

For testing I ran:
```bash
$ tar -tf ${package-name}*.pkg.tar.xz
```

In the Task Manager I noticed `xz.exe` does not seem to be doing anything, but when interrupting `tar` with `CTRL+C`, it starts utilizing 50% of the CPU with no end in sight.

Yesterday I thought I was able to circumvent the problem by disabling Windows Defender, but that's not working anymore, so I might as well be remembering it falsely.

I need this functionality for making a standalone distribution of my package.
Do you have any suggestion on how to handle this?

**Comment by mwkroening** [comment]
I forgot to add that installing packages via pacman works fine.
What mechanism is pacman using to extract the packages?

**Comment by mwkroening** [comment]
I tried extracting the package using 7-zip and compressed it again with `tar`.
The so created tarball can be listed and extracted with `tar` without any problem.

**Comment by mwkroening** [comment]
A workaround is filtering the package through `xz` manually by replacing
```bash
$ tar --file ${package-name}*.pkg.tar.xz
```
with
```bash
$ xz --decompress --stdout ${package-name}*.pkg.tar.xz | tar --file -
```

**Comment by jdtournier** [comment]
I'm also facing exactly this issue. I'm trying to build a stripped-down release-only version of Qt5, but `makepkg` hangs at the `tar xJf` stage. I've edited the `PKGBUILD` with the above fix, and hopefully that'll allow me to get on with what I'm trying to do - but it would still be good to get this fixed...

Using the explicit `xz --stdout | tar` change seems to at least allow some progress to be made, but I'm noticing now that this also appears to hang, with `xz` showing no CPU usage, `bsdtar` showing ~4%, and the Windows AntiMalware service working overtime at ~30%. Might be related...?

I'll see what happens if I disable the AntiMalware service - just need to figure out how...

**Comment by jdtournier** [comment]
OK, turning off Windows Defender's real-time protection seems to allow the `xv | tar` pipeline to complete, but makes no difference to the direct `tar xJf` call...

**Comment by Hugobros3** [comment]
Issue still persists to this day, `tar xf whatever.tar.xz` results in a hang and idling bsdtar/xz processes, if I try to kill it using ctrl-c, it lives on in task manager, starts spinning on a thread and does no IO.

**Comment by Biswa96** [comment]
Can you provide a link of that taball as example?

**Comment by Hugobros3** [comment]
It's none other than LLVM 10 https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/llvm-project-10.0.1.tar.xz

**Comment by Biswa96** [comment]
First of all, tar, more specifically GNU tar, **does not** hang in my system. But there is a catch. GNU tar can not handle symbolic link here. If the tarball contains symlinks there will be some warnings like this:

```
tar: xyz: Cannot create symlink to ‘xyz’: No such file or directory
tar: Exiting with failure status due to previous errors
```

But the normal remaining files and folders will be extracted as usual. To solve this symlink issue, just use `bsdtar` command instead of `tar`.

**Comment by Hugobros3** [comment]
The issue is not that I can't extract a tarball, I can use 7zip to do it by hand (or run `xz -d` or a multitude of other things), the issue is this breaks any script depending on that functionality. Its also unrelated to the symlink issue since regular `tar`does not even get to that point, it just hangs.

**Comment by krystalgamer** [comment]
Facing the same issue, it worked a few months ago which is weirder

**Comment by rivanfebrian123** [comment]
Is it possible to replace the MINGW64 `tar` with the base one (since it works really fine, and it's just a command, not a library)?

**Comment by revelator** [comment]
facing a similar issue after the last update packages compressed with xz refuse to unpack :S it only uncompresses to a .tar then fails... 

```
/src/gcc/mingw-w64-binutils/PKGBUILD: line 61: cd: /E/mingw-w64-binutils/src/binutils-2.39: No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by Biswa96** [comment]
> facing a similar issue after the last update packages compressed with xz 

I can not reproduce that issue. Here is a small portion of the output of `makepkg-mingw --nobuild` command in MINGW-packages/mingw-w64-binutils

```
==> Verifying source file signatures with gpg...
    binutils-2.39.tar.xz ... Passed
==> Extracting sources...
  -> Extracting binutils-2.39.tar.xz with bsdtar
==> Starting prepare()...
  -> Applying 0002-check-for-unusual-file-harder.patch
patching file binutils/bucomm.c
Hunk #1 succeeded at 618 with fuzz 2 (offset 43 lines).
Hunk #2 succeeded at 637 (offset 28 lines).
...many more
```

You can also check the build in CI with a pkgrel bump in mingw-w64-binutils/PKGBUILD file.

**Comment by revelator** [comment]
well it broke everything here pacman no longer works after updating :S im getting a ton of errors on even the simplest command.
pacman -Syuu says everything is upto date but can no longer build any package itself instead it spews a large list of errors related to some pacman variables which no longer seem to be defined. guess i need to reinstall everything sigh.

**Comment by Biswa96** [comment]
Most of the time antivirus program does random thing to msys2 installation, so make sure check that aspect.

Other than that external cause, this issue did not happen since 2021. Feel free to open this issue if it is reproducible.

**Comment by revelator** [comment]
hmm in that case it would seem microsofts internal antivirus is ignoring the fact that i have whitelisted the entire directory (well that would suck), not getting any warnings from it intercepting something and the log does not show anything either so im not sure this would be the culprit. could be database corruption as i have a pretty large toolset (any way to check that ?).

**Comment by Biswa96** [comment]
As you are compiling mingw-w64-binutils, it was recently rebuilt tomorrow to fix an issue, see this commit https://github.com/msys2/MINGW-packages/commit/abc14e18c5c5deddee7ef1e1635ddf9105b8fd0d. You can see the build log in that commit's pull request.

**Comment by revelator** [comment]
aye i allready added those before they got committed :).
the msys2 version i was using was pretty old originally, but i been updating it pretty often. cannot say which package broke the camels back but after the upgrade to the new msys2 runtime it started behaving a bit weird and shortly after it just broke completely.
