### ISSUE TITLE
mingw-w64-x86_64-python3 has the wrong path separator (os.sep)

### ISSUE THREAD

**Issue by znark** [msys2/MSYS2-packages#1591]
MinGW64 subsystem Python 3 (installed via `pacman -S mingw64/mingw-w64-x86_64-python3`) seems to give a surprising result as the operating system path separator (the `os.sep` variable in Python’s standard `os` module):

```
$ which python3
/mingw64/bin/python3

$ python3 check.py
repr(os.linesep)     : '\r\n'
os.name              : nt
os.pathsep           : ;
os.sep               : /
platform.system()    : Windows
sys.platform         : win32
sys.version          : 3.7.2 (default, Dec 25 2018, 05:36:22)  [GCC 8.2.1 20181214 64 bit (AMD64)]
os.environ['PATH']   : C:\msys64\mingw64\bin;C:\msys64\home\Aho\bin;C:\msys64\mingw64\bin;C:\msys64\usr\local\bin;C:\msys64\usr\bin;C:\msys64\usr\bin;C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\msys64\usr\bin\site_perl;C:\msys64\usr\bin\vendor_perl;C:\msys64\usr\bin\core_perl;C:\local\boost_1_68_0\lib64-msvc-14.1
os.path.join('a','b'): a/b
```
(`check.py`, which produces the above output, is a simple script from https://github.com/conan-io/conan/issues/2638#issuecomment-377393270)

Having `os.sep` as `/` instead of `\` in native Windows environment breaks things such as trying to split a path to its components by doing the following:

```
$ python3
Python 3.7.2 (default, Dec 25 2018, 05:36:22)  [GCC 8.2.1 20181214 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> path = r'C:\Foo\Bar\Bah'
>>> path.split(os.sep)
['C:\\Foo\\Bar\\Bah']
>>>
``` 

Also, `os.path.join` will produce paths that are strange to the native Windows environment (even though forward slashes often work in Windows to some extent).

**Comment by StarWolf3000** [comment]
Do the following: Execute this script (using the same Python interpreter instance) from both inside a CMD window (without utilizing bash) and inside a shell (bash for example) from MinTTY terminal emulator. You may be surprised by its output.

In CMD, `C:\msys64\mingw64\bin\python3.exe check.py` should give you 
```
os.sep               : \
```

It does for me at least.

**Comment by znark** [comment]
Correct. When `C:\msys64\mingw64\bin\python3.exe` is run in plain `CMD.EXE` (launched through the Windows Start menu without touching the MSYS2 environment at all), it will give `os.sep` as `\`. 

However, if `CMD.EXE` is launched as a subshell of the MSYS2 MINGW64 Bash shell – either directly in MinTTY, or via the `/usr/bin/start` command, which will launch it in a separate console window – the MinGW64 Python 3 will still give `os.sep` as `/` in such instance of CMD.EXE, just like when run from plain Bash.

Curious. What does it mean?

Regardless of the way the MingGW64 version of Python 3 is launched, I think it should always give `os.sep` as `\` since it is a version of Python that *should not know anything about POSIX paths* – and that indeed consistently uses Windows paths (with drive letters and backslashes) in its `sys.path` list, as it should. If one wants a POSIX Python for the MSYS2 environment, they should install the MSYS version instead of the MinGW64 version.

**Comment by Alexpux** [comment]
@znark under bash shell separator must be ````/```` in other case it will be eated by shell and not all msys2 utils understand this separator.

**Comment by lazka** [comment]
To summarize:

* It uses / by default to improve interoperability with cygwin executables
* You can disable it by unsetting the MSYSTEM env var `MSYSTEM= python.exe`
* / is a valid separator under Windows, so supporting paths with that is a good idea anyway (use os.path.normpath or os.path.split)

**Comment by mingwandroid** [comment]
.. and your python code should use literal / (e.g. getting filenames from known posix subprocess calls) and \ (getting file names from windows apis) when appropriate and os.sep (in general and esp. when emitting filenames to a log or passing them to the shell) when appropriate.

We made this choice to switch it based on MSYSTEM years ago and I still think it is the right thing to do (thanks for continuing to maintain the patch!). Many upstream python projects have cleaned their code-bases of bad assumptions around this matter due to this change.

**Comment by jdpipe** [comment]
I think that this trick of changing `os.path.sep` depending on the presence/absence of `$MSYSTEM` makes for very confusing behaviour, and I suspect it is the wrong design choice, although I don't know what other upstream impacts there might be.

As a simple example of what I would say is broken behavior arising from this approach: 

```
import pathlib
import subprocess

p = pathlib.Path("mytest/")
p.mkdir(parents=True, exist_ok=True)
fp = p / "myscript"
with fp.open("w",encoding="utf8") as f:
	f.write("#!/usr/bin/env python3\n")
	f.write("print('hello from python')\n")
print("script written to",fp)
subprocess.run(str(fp))
```

This example attempts to create a script in a subdirectory and run it using `subprocess.run`. However, MINGW64/UCRT64 Python messes up `os.path.sep`, making `pathlib` do the wrong thing when converting the path in the call to `subprocess.run`. This script as written will work fine in Linux, but fails in MSYS MINGW64 Python.

Further compounding the problem is the fact that one cannot use `subprocess.run(...,shell=True)` to fix this behaviour, because MINGW64 Python still uses `cmd` as the shell. So the selected shell is not `bash` and does not understand `/`-separated paths.

I struggle to understand the use-case that justifies this `$MSYSTEM`-dependent behaviour in MINGW64/UCRT64 versions of Python.... Can you explain more?

(PS Of course another factor is that shebangs are not supported in Windows. That is beside the point for this example. The point is that you can't use `str` to convert a `pathlib.Path` for embedding into a `subprocess.run` command, which seems to be breaking a very core Python functionality. )

**Comment by jdpipe** [comment]
I further note that native Windows Python always uses the same `os.path.sep` of `\`, irrespective of its execution environment. Personally, I expected MINGW64 Python to have the same behaviour as true native Python. The implemented behaviour was not expected. If I had been using MSYS (as opposed to MINGW64) Python, then yes, I would expect `/` instead (and I would expect `bash` to be the shell used by `subprocess.run`)
