### ISSUE TITLE
openssh: sftp prompt broken

### ISSUE THREAD

**Issue by cw789** [msys2/MSYS2-packages#1697]
I open this issue to have it documented here.
Initial reported at: https://github.com/git-for-windows/git/issues/2257

Command:
```
sftp hostname
```
Expected:
```
sftp>_
```
Got:
```
s     _
```

**Comment by MNeuling** [comment]
The behaviour of the prompt is very disturbing. If you use auto completion or backspace the whole typed command is invisible. The bug makes the sftp command nearly unusable.

Is there a plan to fix it?

**Comment by edwardbeckett** [comment]
I'm having the same issue. After logging in via sftp the prompt is broken and path navigation is very difficult. 

![sftp](https://user-images.githubusercontent.com/949373/67001278-f6586d00-f09e-11e9-80c7-313eaffba35c.png)

**Comment by JulienCochuyt** [comment]
Same issue here using sftp invoked from MinTTY as shipped with Git for Windows
Any hint on how we could help diagnose/fix this?
Older versions did not exhibit this faulty behavior, but I cannot recall what was the last working one.

**Comment by lhmouse** [comment]
ping?

**Comment by Tantalus13A98B5F** [comment]
It's an issue caused by `libedit`, who mixed the use of `wint_t` and `wchar_t`. On real Linux (here Ubuntu 20.04 amd64) these two types are identical, but on MSYS2 `wchar_t` is only half of `wint_t`. Thus when you are passing `wint_t[]` to an argument of type `wchar_t*`, the program will take as if the wide-string has only one character, making it an MSYS2-specific bug.

A true fix of this problem should wait until `libedit` have their code refactored and come to a portable type definition. For a quickfix (caveat: don't know if this would be causing new problems), try the following patch with `libedit/src/el.h`, then recompile `libedit` and `openssh`:

```diff
120,121c120,121
<       wint_t          **el_display;   /* Real screen image = what is there */
<       wint_t          **el_vdisplay;  /* Virtual screen image = what we see */
---
>       wchar_t         **el_display;   /* Real screen image = what is there */
>       wchar_t         **el_vdisplay;  /* Virtual screen image = what we see */
```

**Comment by cw789** [comment]
Close now as https://github.com/msys2/MSYS2-packages/pull/2241 is merged.
Thanks a lot @Tantalus13A98B5F .
