### ISSUE TITLE
pacman-key crash with POSIXLY_CORRECT

### ISSUE THREAD

**Issue by nu8** [msys2/MSYS2-packages#1955]
The script at `etc/post-install/07-pacman-key.post` looks similar to this:

~~~
pacman-key --init
pacman-key --populate msys2
pacman-key --refresh-keys
~~~

It turns out that `pacman-key` is a Bash script. I noticed that if you have
`POSIXLY_CORRECT` defined, it causes error:

~~~
pacman-key: line 195: syntax error near unexpected token `<'
~~~

Here is the code in question:

~~~sh
mapfile -t ids < <("${GPG_PACMAN[@]}" --search-keys --batch \
--with-colons "$1" 2>/dev/null | awk -F: '$1 == "pub" { print $2 }')
~~~

The `<()` construct is not defined by POSIX. The output to that command looks
like this:

~~~
info:1:9
pub:B91BCF3303284BF90CC043CA9F418C233E652008:1:2048:1411983334::
uid:Ignacio Casal Quinteiro <icquinteiro@gmail.com>:1411983334::
pub:53DC60288EADD731CCD33689845B56DB56E967B6:1:1024:1402882381::r
uid:Ignacio Casal Quinteiro <nacho.resa@gmail.com>:1407202211::
pub:2D060D176C9F5FA6F779D4F4D3AA734419706E95:1:1024:1376348923:1378163323:
uid:marcel quinteiro (atividade 1) <m.k9999@hotmail.com>:1376348923::
~~~

Then after AWK:

~~~
B91BCF3303284BF90CC043CA9F418C233E652008
53DC60288EADD731CCD33689845B56DB56E967B6
2D060D176C9F5FA6F779D4F4D3AA734419706E95
~~~

and the only thing that is tested, is the number of IDS. So an array is not even
needed. It could just be something like this:

~~~sh
ids=$("${GPG_PACMAN[@]}" --search-keys --batch \
--with-colons "$1" 2>/dev/null |
awk 'index($0, "pub:") == 1 { n1++ } END { print n1 }')
~~~

I checked, and it seems the problem is upstream too:

<https://archlinux.org/packages/core/x86_64/pacman>

So I am not sure if MSYS2 is interested to fix it. But if so, the fix is above.
Until this is resolved, I am just bypassing `pacman-key` entirely. Here is a
replacement script:

~~~sh
export GNUPGHOME=/etc/pacman.d/gnupg
mkdir -p "$GNUPGHOME"
touch "$GNUPGHOME"/pubring.gpg
gpg --import /usr/share/pacman/keyrings/msys2.gpg
gpg --import-ownertrust /usr/share/pacman/keyrings/msys2-trusted

gpg --batch --gen-key <<eof
Key-Type: RSA
Name-Email: pacman@localhost
%no-protection
eof

while read s_key
do
   s_trim=${s_key%%:*}
   gpg --command-fd 0 --lsign-key "$s_trim" <<eof
y
eof
done < /usr/share/pacman/keyrings/msys2-trusted
~~~

**Comment by eli-schwartz** [comment]
Is there a particular reason to be running unknown programs with POSIXLY_CORRECT? Programs with a `#!/bin/bash` shebang often use this bash-specific functionality which `set -o posix` will turn into an error.

**Comment by muv1** [comment]
Its in my profile:

https://github.com/muv1/hearth/blob/master/msys2/.profile

and honestly its just good practice. Scripts should be POSIX compatible unless its unreasonable to conform. In this case, its trivial to switch to a POSIX idiom, and doesnt cost any additional subshells. Its likely better as it doesnt create a temp file like the original code.

**Comment by eli-schwartz** [comment]
This is one of 3 uses of <() in pacman-key, with another 2 in repo-add, and 21 uses in makepkg. Have you looked into all those other cases too?

I dispute the notion that scripts with a /bin/bash shebang must avoid bash-specific syntax which is a syntax error under ash or other strictly POSIX sh implementations. It's unfortunate that bash POSIX mode restricts the use of it, since POSIXLY_CORRECT should in truth NOT be about "remove bash features from bash", but rather be about siding with the POSIX interpretation of a feature when the GNU tool violates a POSIX requirement by default.

<() doesn't violate POSIX as far as I'm aware, POSIX doesn't state that unspecified syntax must abort with a syntax error. bash in POSIX mode supports arrays, `arr=(one two three)` is a syntax error on ash shells, but bash in POSIX mode permits it and defines a bash array.

I believe people would be better served if bash did *NOT* ban this under POSIX mode, but instead people who wanted to write /bin/sh compatible scripts would just... not use bash as their /bin/sh symlink, to test that the script works under strictly POSIX compliant conditions. Instead, POSIXLY_CORRECT makes bash into some weird quasi-state where it's intended to serve as a /bin/sh replacement, and thus disables some but not all bashisms, but doesn't properly distinguish between "invoked as /bin/sh" and "invoked with POSIXLY_CORRECT", and to be honest, I think it then fails at both.

**Comment by eli-schwartz** [comment]
If you still believe this is a problem, I invite you to begin a discussion on the pacman development list: https://lists.archlinux.org/listinfo/pacman-dev

**Comment by eli-schwartz** [comment]
> I believe people would be better served if bash did _NOT_ ban this under POSIX mode

Incidentally, I've just noticed this is already the case on the devel branch. From the bash 5.1-alpha NEWS file:

> u. Process substitution is now available in posix mode.

From CWRU.chlog:
```
				   1/17
				   ----
parse.y,subst.c
	- process_substitution: now available in POSIX mode. Most recently
	  requested by Martijn Dekker <martijn@inlv.org>; requested several
	  times in the past
```
