### ISSUE TITLE
Bad address on some path conversions

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#2282]
```
#!/bin/bash
# this isn't supposed to work, just some parameters and calling a random mingw executable
/mingw64/bin/gcc.exe --foreign-types=C:/qt5/pkg/mingw-w64-x86_64-qt5,C:/qt5/pkg/mingw-w64-x86_64-qt5
```

```
$ bash a.sh
a.sh: line 2: /mingw64/bin/gcc.exe: Bad address
```

Looks like the path conversion code errors out, but it's erratic, so likely a memory corruption.

Adding `export MSYS2_ARG_CONV_EXCL='*'` makes it work

Possibly related: https://github.com/m-ab-s/media-autobuild_suite/issues/1584

**Comment by dg0yt** [comment]
Still reproducable...
The error goes away if another command is called first. Even `:` is enough. The output is surprising:
~~~
gcc.exe: error: unrecognized command-line option '--foreign-types=C;D:\msys64\qt5\pkg\mingw-w64-x86_
64-qt5,C;D:\msys64\qt5\pkg\mingw-w64-x86_64-qt5'
gcc.exe: fatal error: no input files
compilation terminated.
~~~

**Comment by dg0yt** [comment]
IIUC in `C:/qt5/pkg/mingw-w64-x86_64-qt5,C:/qt5/pkg/mingw-w64-x86_64-qt5`
we assume a mixed (`cypath -m`) path list, separated by `;`, but  
`bash`/MSYS2 assumes a Unix (`cypath -u`) path list, separated by `:`, transforming

`C` -> `C`
`/qt5/pkg/mingw-w64-x86_64-qt5,C` -> `D:\msys64\qt5\pkg\mingw-w64-x86_
64-qt5,C`
`/qt5/pkg/mingw-w64-x86_64-qt5` -> `D:\msys64\qt5\pkg\mingw-w64-x86_
64-qt5`

(given my MSYS2 installation in `D:\msys64`)

That is just the unexpected part of the successful conversion when calling MINGW64 from MSYS2.
It doesn't explain the "Bad address".

**Comment by dg0yt** [comment]
> Adding `export MSYS2_ARG_CONV_EXCL='*'` makes it work

Any non-empty value makes it work...

**Comment by dg0yt** [comment]
I have a working fix: Change
https://github.com/msys2/MSYS2-packages/blob/174fcf6fcedea5d9cb024864ab37d691b23a81e0/msys2-runtime/0004-Add-functionality-for-converting-UNIX-paths-in-argum.patch#L992
to
~~~diff
+  memset (stack_path, 0, stack_len);
~~~
which is the allocated size. The output changes to
~~~
gcc.exe: error: unrecognized command-line option '--foreign-types=C:/qt5/pkg/mingw-w64-x86_64-qt5,C:/qt5/pkg/mingw-w64-x86_64-qt5'
~~~
I'm curious if this can fix other rare cases of "Bad address".

Starting at the path conversion entry point, there seems some room for reducing the number of allocations. Maybe it would also be better to save some reallocations instead of saving 5 bytes of allocated memory in the context of argument conversion. But I have difficulties to see how I can effectively develop and contribute modification, give the pile of patches.

**Comment by lazka** [comment]
The source of the patches is here: https://github.com/msys2/msys2-runtime

**Comment by dg0yt** [comment]
Sure, and the tests are there: https://github.com/dg0yt/msys2-tests...

**Comment by dg0yt** [comment]
Apart from not getting "Bad address", what is the expected conversion of `--foreign-types`?
