### ISSUE TITLE
MAKEFLAGS set to "nproc+1"?

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MSYS2-packages#2692]
## Describe the issue

makepkg_mingw.config set MAKEFLAGS to "nproc+1"! Why there is "+1", I got some failure about make jobserver. and I think that this is its origin
https://github.com/msys2/MSYS2-packages/blob/master/pacman/makepkg_mingw.conf#L126

**Comment by mati865** [comment]
On Linux with HDD it gives slightly faster builds, I think it's because of IO. Haven't tested this with SSD, instead just kept old good +1.
If it's really the IO then I'd expect even bigger gains on Windows because of how bad the filestsyems are compared to Linux.

Ninja defaults to +2 BTW.

> I got some failure about make jobserver. and I think that this is its origin

I doubt it's related to number of threads, rather make/msys2-runtime bug.
