### ISSUE TITLE
tar cannot work with symlinks and thinks directory does not exist

### ISSUE THREAD

**Issue by SamTV12345** [msys2/MSYS2-packages#3941]
### Description / Steps to reproduce the issue

1. Checkout this pull request https://github.com/ether/etherpad-lite/pull/5861
2. Use the script in src/bin/buildForWindows.sh
3. It works locally but as soon as I upload that to github action and it executes this template: https://github.com/msys2/setup-msys2 it fails and says that it cannot finds it

This has worked previously e.g. here: https://github.com/ether/etherpad-lite/actions/runs/5522205465/job/14951997611 
From one day to another the script failed.

### Expected behavior

It tars all the files so we can upload it to github.

### Actual behavior

Run set MSYSTEM=winsymlinks:lnk
bin: directory # Output of file -L command
create a clean environment in /tmp/tmp.I9[8](https://github.com/ether/etherpad-lite/actions/runs/5772996726/job/15648526101?pr=5861#step:7:9)pRKfCri...
tar: bin: Cannot create symlink to ‘src/bin’: No such file or directory
tar: Exiting with failure status due to previous errors
ERROR: 'tar xf -' failed
ERROR: failed to copy etherpad to temporary folder
cleaning up...
Error: Process completed with exit code 1.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Github Action Windows build

**Comment by alex-tee** [comment]
i think https://github.com/msys2/MSYS2-packages/pull/3946 fixes this

**Comment by SamTV12345** [comment]
That is great. Hopefully this is merged soon. Our windows build pipeline is currently 2-3 times longer because I manually copy all the files from one location into the temp directory. With tar it was much more efficient.

**Comment by cbrt64** [comment]
BTW, it should be `set MSYS=winsymlinks:lnk`, not `set MSYSTEM=winsymlinks:lnk`. HTH.

**Comment by SamTV12345** [comment]
> BTW, it should be `set MSYS=winsymlinks:lnk`, not `set MSYSTEM=winsymlinks:lnk`. HTH.

The docs says:

The environment can be later overridden using the MSYSTEM environment variable if needed. This is useful when multiple commands need to be executed in different contexts. For example, in order to build a PKGBUILD file and then test the installed artifact

With MSYS nothing was working suddenly.

**Comment by cbrt64** [comment]
I see you've [switched](https://github.com/ether/etherpad-lite/pull/5861/commits/0ffcc322fb8d59ab3e74c2dc96109d7b79eefb64) from `tar xf` to `git checkout`, so this infodump might not be as useful to you as it could have been. But just to be clear on those environment variables:

`$MSYSTEM` gets set to the current build environment, e.g. MSYS, MINGW64, UCRT64, etc.
`$MSYS`, on the other hand, is MSYS2's equivalent of the [`$CYGWIN` settings variable](https://cygwin.com/cygwin-ug-net/using-cygwinenv.html). Oddly enough, I can't find this in the documentation per se, though it can be found many other places:
* [The /*.ini files](https://github.com/msys2/msys2-launcher/blob/master/launcher.ini) (in your root directory),
* [This commit message](https://github.com/msys2/msys2-runtime/commit/38482c8a8a4c6a1a0f955cd8ddc5068d1b0df863),
* [This news item](https://www.msys2.org/news/#2022-09-24-changed-behavior-for-empty-env-vars), etc.

MSYS2 cannot normally create symlinks to non-existent files. So because your tarball suddenly has the symlink entry `bin -> src/bin` before `src/` is created, tar will fail. (Maybe there was a recent file-ordering change in `git archive`?) The traditional kludge in such a case has been to do `tar -xf foo || true` to ignore the missing symlinks (though that doesn't help if you actually need them).

`MSYS=winsymlinks:lnk`, specifically, tells MSYS2 to use non-special CYGWIN .lnk files as a more-compatible symlink, so e.g. `ln -s nofile link` will work as expected. But `tar` has some other hang-ups in this regard, so I'm pretty sure if you were to just roll back your build script changes and use `bsdtar` it would work again.

**Comment by SamTV12345** [comment]
> 

Thanks for the reply. The problem was that it started to fail sometime without any change. The directories are definetely there. But somehow msys couldn't locate them.

**Comment by SamTV12345** [comment]
Closing. It somehow works again while I did not change anything in the configuration. I wish all my problems would go away that easily. Haha 😄
