### ISSUE TITLE
problem to building module virtiofs 

### ISSUE THREAD

**Issue by lystrys2030** [msys2/MSYS2-packages#3977]
hi

I would like to add the virtiofs module to qemu I have downloaded the git clone https://gitlab.com/virtio-fs/qemu.git
I found the following command "./configure --prefix=$PWD --target-list=x86_64-softmmu" but I got an error when I run it in msys2 environment "ERROR: Unrecognized host OS ( uname -s reports 'MSYS_NT-10.0-
22621'" how do I run the ./configure and then the make -j${PROC} command?

Thank you for your help

**Comment by Biswa96** [comment]
Use any environment other than MSYS (purple icon). More info about the environments can be found here https://www.msys2.org/docs/environments/

If you want to compile qemu for x86_64 host, then UCRT64 is recommended.

**Comment by sskras** [comment]
I guess building on emulated POSIX environments like Cygwin and pure MSYS2 is not supported in the official repo:
https://wiki.qemu.org/Hosts/W32#Native_builds_with_Cygwin

> Builds with the normal Cygwin compiler are not supported. Nevertheless, cygwin can be used as a build environment because it also contains all necessary Mingw-w64 packages.

The same seems to be valid for MSYS2. If you point `configure` to MinGW-GCC compiler on these environments, it should build the thing:
https://wiki.qemu.org/Hosts/W32#Native_builds_with_MSYS2

> * Next install the basic set of developer tools:
> ```
> pacman -S base-devel mingw-w64-x86_64-toolchain git python ninja
> ```
> ...
> * Close the MSYS2 console.
> * Start mingw64.exe.

And if you want to build a POSIX-on-Windows version of QEMU rather than a native (WinAPI/MinGW) build, I guess better luck is to ask the developers directly: https://www.qemu.org/contribute/

**Comment by lystrys2030** [comment]
think you for your answer and your recommendations

**Comment by sskras** [comment]
PS. Actually I see QEMU being built on Midipix already:
https://dev.midipix.org/build/midipix_build/blob/main/f/patches/qemu-3.1.0.local.patch

... only that state of Midipix is still marked as pre-alpha and has no installer (requires cross-building and extracting the whole distro by hand).

**Comment by lystrys2030** [comment]
think I 've read it
