### ISSUE TITLE
Is there a 'script' command?

### ISSUE THREAD

**Issue by Shreeshrii** [msys2/MSYS2-packages#54]
Hi Alex,

I would like to capture the terminal output into a text file. I understand that the script command can do this by creating a typescript file.

Is this available? If not, is there any alternative?

Thanks,
Shree

**Comment by sskras** [comment]
The `script.exe` is already present.  I guess the bug is fixed:

```cmd
saukrs@DESKTOP-O7JE7JE MSYS ~
$ uname -a
MSYS_NT-10.0-19044 DESKTOP-O7JE7JE 3.3.6-341.x86_64 2022-10-24 08:25 UTC x86_64 Msys

saukrs@DESKTOP-O7JE7JE MSYS ~
$ pacman -Qo `which script.exe`
/usr/bin/script.exe is owned by util-linux 2.35.2-3
```

The **util-linux** package was added on Oct 13, 2014 by @Alexpux:
commit 2c21d28471baa0a1cb870d389b462493548d8097 [util-linux: New package.](https://github.com/msys2/MSYS2-packages/commit/2c21d28471baa0a1cb870d389b462493548d8097#diff-4e6630ed081a1c833dd85190cccf75624a532ffda46ec70fe7884df9ee745ea7)
