### ISSUE TITLE
msys2 uninstaller freezing.

### ISSUE THREAD

**Issue by divinity76** [msys2/MSYS2-packages#663]
first it would say that the entire installation directory would be removed, which would be impressive considering the installer runs from that directory (impressive, not impossible), but that didn't happen, next the uninstaller froze at 100%, the last log output being: 

> C:\msys2_64\etc\pacman.d
> C:\msys2_64\etc\fstab.d
> C:\msys2_64\etc
> 
> Uninstallation completed successfully.

now, the "uninstall" and "cancel" buttons are both greyed out, and when i press the right-corner-x, it will ask "do you want to cancel the uninstallation process?", and it's just stuck on 100% indefinitely. 
i was expecting a "finish" button or similar. 

![](http://image.prntscr.com/image/7c70ee655c2a48ee932c3aba134a16b9.png)

**Comment by i-give-up** [comment]
Mine looked the same (100%, buttons greyed out) but after a minute or so, it proceeded to a new dialog that allowed me to quit.

**Comment by Biswa96** [comment]
This only happens when antivirus or antimalware program prevents the installation or uninstallation process. Most of the time msys2 flagged as malware. Please report the false positive detection to the antivirus software vendor. Or exclude the msys2 installation directory from scanning in that antivirus.
